name: data_science_time_series_forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pytest
  - black
  - flake8
  - mypy
  - pip
  - seaborn
  - pip:
    - pretty_errors 
    - gdown
    - xgboost
    - CatBoost
    - lightgbm
    - keras
    - tensorflow
    